// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// combinationsWithRepetition_counts
List combinationsWithRepetition_counts(int n, int r);
RcppExport SEXP _fastpeRmute_combinationsWithRepetition_counts(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(combinationsWithRepetition_counts(n, r));
    return rcpp_result_gen;
END_RCPP
}
// permutationsWithRepetition_counts
List permutationsWithRepetition_counts(int n, int r);
RcppExport SEXP _fastpeRmute_permutationsWithRepetition_counts(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(permutationsWithRepetition_counts(n, r));
    return rcpp_result_gen;
END_RCPP
}
// combinationsWithRepetition
IntegerMatrix combinationsWithRepetition(int n, int r);
RcppExport SEXP _fastpeRmute_combinationsWithRepetition(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(combinationsWithRepetition(n, r));
    return rcpp_result_gen;
END_RCPP
}
// combinationsWithRepetitionTest
IntegerMatrix combinationsWithRepetitionTest(int n, int r);
RcppExport SEXP _fastpeRmute_combinationsWithRepetitionTest(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(combinationsWithRepetitionTest(n, r));
    return rcpp_result_gen;
END_RCPP
}
// combinationsWithoutRepetition
IntegerMatrix combinationsWithoutRepetition(int n, int r);
RcppExport SEXP _fastpeRmute_combinationsWithoutRepetition(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(combinationsWithoutRepetition(n, r));
    return rcpp_result_gen;
END_RCPP
}
// permutationsWithoutRepetition
IntegerMatrix permutationsWithoutRepetition(int n, int r);
RcppExport SEXP _fastpeRmute_permutationsWithoutRepetition(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(permutationsWithoutRepetition(n, r));
    return rcpp_result_gen;
END_RCPP
}
// permutationsWithRepetition
IntegerMatrix permutationsWithRepetition(int n, int r);
RcppExport SEXP _fastpeRmute_permutationsWithRepetition(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(permutationsWithRepetition(n, r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastpeRmute_combinationsWithRepetition_counts", (DL_FUNC) &_fastpeRmute_combinationsWithRepetition_counts, 2},
    {"_fastpeRmute_permutationsWithRepetition_counts", (DL_FUNC) &_fastpeRmute_permutationsWithRepetition_counts, 2},
    {"_fastpeRmute_combinationsWithRepetition", (DL_FUNC) &_fastpeRmute_combinationsWithRepetition, 2},
    {"_fastpeRmute_combinationsWithRepetitionTest", (DL_FUNC) &_fastpeRmute_combinationsWithRepetitionTest, 2},
    {"_fastpeRmute_combinationsWithoutRepetition", (DL_FUNC) &_fastpeRmute_combinationsWithoutRepetition, 2},
    {"_fastpeRmute_permutationsWithoutRepetition", (DL_FUNC) &_fastpeRmute_permutationsWithoutRepetition, 2},
    {"_fastpeRmute_permutationsWithRepetition", (DL_FUNC) &_fastpeRmute_permutationsWithRepetition, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastpeRmute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
