# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combinationsWithRepetition_counts <- function(n, r) {
    .Call(`_fastpeRmute_combinationsWithRepetition_counts`, n, r)
}

permutationsWithRepetition_counts <- function(n, r) {
    .Call(`_fastpeRmute_permutationsWithRepetition_counts`, n, r)
}

combinationsWithRepetition <- function(n, r) {
    .Call(`_fastpeRmute_combinationsWithRepetition`, n, r)
}

combinationsWithRepetitionTest <- function(n, r) {
    .Call(`_fastpeRmute_combinationsWithRepetitionTest`, n, r)
}

combinationsWithoutRepetition <- function(n, r) {
    .Call(`_fastpeRmute_combinationsWithoutRepetition`, n, r)
}

permutationsWithoutRepetition <- function(n, r) {
    .Call(`_fastpeRmute_permutationsWithoutRepetition`, n, r)
}

permutationsWithRepetition <- function(n, r) {
    .Call(`_fastpeRmute_permutationsWithRepetition`, n, r)
}

